--- 
- si: true
  name: Celsius
  quantity: temperature
  uuid: a3553014-4174-11de-aad1-001ff3caa767
  id: 1
  unit_symbol_text: degC
  base_unit: 
  unit_symbol: C
  description: Celsius is a unit of temperature.
- si: true
  name: meter
  quantity: length
  uuid: a3560020-4174-11de-aad1-001ff3caa767
  id: 2
  unit_symbol_text: m
  base_unit: true
  unit_symbol: m
  description: Meters are a standard SI unit of length.
- si: true
  name: meters per second
  quantity: velocity
  uuid: a39ad2c2-4174-11de-aad1-001ff3caa767
  id: 3
  unit_symbol_text: m/s
  base_unit: 
  unit_symbol: m/s
  description: Meters per second is a standard SI unit for velocity.
- si: 
  name: "revolutions per second "
  quantity: " rotational speed"
  uuid: a39e193c-4174-11de-aad1-001ff3caa767
  id: 4
  unit_symbol_text: S
  base_unit: 
  unit_symbol: S
  description: "rotational speed -- not angular velocity which would be degrees or radians per second. "
- si: 
  name: gauss
  quantity: magnetic field
  uuid: 5edceb9a-b4a2-11e0-b78f-e80688fffebc
  id: 5
  unit_symbol_text: G
  base_unit: 
  unit_symbol: G
  description: "gauss"
