development: &non_production_settings
  site_name: Investigations (development)
  site_url: http://localhost:3000
  description: ""
  default_admin_user: &default_admin_user
    login: stephen
    email: stephen.bannasch@gmail.com
    first_name: Stephen
    last_name: Bannasch
  enable_default_users: true
  include_otrunk_examples: false
  site_district: Investigations-district
  site_school: Investigations-school
  states_and_provinces: &states_and_provinces
    - MA
  active_school_levels: &active_school_levels 
    - "2"
    - "3"
    - "4"
  active_grades: &active_grades 
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
  active_grades: *active_grades
  theme: default
  help_email: investigations@concord.org
  maven_jnlp_families:
    - "all-otrunk-snapshot"
  maven_jnlp_servers:
    - :name: concord
      :host: http://jnlp.concord.org
      :path: /dev/org/concord/maven-jnlp/
  default_maven_jnlp:
    server: concord
    family: all-otrunk-snapshot
    version: snapshot
  net_logo_package_name: otrunknl4
  
test:
  <<: *non_production_settings

cucumber:
  <<: *non_production_settings

staging:
  site_name: Investigations (staging)
  site_url: http://investigations.staging.concord.org
  description: ""
  default_admin_user: *default_admin_user
  enable_default_users: true
  include_otrunk_examples: false
  states_and_provinces: *states_and_provinces
  active_school_levels: *active_school_levels 
  active_grades: *active_grades 
  site_district: Investigations-district
  site_school: Investigations-school
  help_email: investigations@concord.org
  maven_jnlp_servers:
    - :name: concord
      :host: http://jnlp.concord.org
      :path: /dev/org/concord/maven-jnlp/
  maven_jnlp_families:
    - "all-otrunk-snapshot"
  default_maven_jnlp:
    server: concord
    family: all-otrunk-snapshot
    version: snapshot
  net_logo_package_name: otrunknl4
  
production:
  site_name: Investigations
  site_url: http://investigations.concord.org
  description: ""
  default_admin_user: *default_admin_user
  enable_default_users: false
  include_otrunk_examples: false
  states_and_provinces: *states_and_provinces
  active_school_levels: *active_school_levels 
  active_grades: *active_grades 
  site_district: Investigations-district
  site_school: Investigations-school
  help_email: investigations@concord.org
  admin_email: npaessel@concord.org
  allow_drafts_in_assignments: false
  maven_jnlp_servers:
    - :name: concord
      :host: http://jnlp.concord.org
      :path: /dev/org/concord/maven-jnlp/
  maven_jnlp_families:
    - "all-otrunk-snapshot"
  default_maven_jnlp:
    server: concord
    family: all-otrunk-snapshot
    version: snapshot
  net_logo_package_name: otrunknl4
