# local ids for RI school districts that should be active in 
# RITES in Fall 2009:
#
#    Coventry    "06"
#    Cranston    "07"
#    Johnston    "16"
#    Lincoln     "17"
#    Scituate    "30"
#    Woonsocket  "39"
#
--- 
development: 
  host: portfolio.ri.net
  username: concord
  password: '*****'
  external_domain_url: http://moleman.concord.org/
  districts:
    - "06"
    - "07"
    - "16"
    - "17"
    - "39"

test: &test_settings
  host: portfolio.ri.net
  username: concord
  password: '*****'
  external_domain_url: http://moleman.concord.org/
  districts:
    - "06"
    - "07"
    - "16"
    - "17"
    - "39"

cucumber:
  <<: *test_settings

staging: 
  host: portfolio.ri.net
  username: concord
  password: '*****'
  external_domain_url: http://test.portfolio.ri.net/
  districts:
    - "06"
    - "07"
    - "16"
    - "17"
    - "39"

production: 
  host: portfolio.ri.net
  username: concord
  password: '*****'
  external_domain_url: http://portfolio.ri.net/
  districts:
    - "06"
    - "07"
    - "16"
    - "17"
    - "39"
