---
production: &prod
  :help_email: itsisu@concord.org
  :site_url: http://itsisu.units.concord.org
  :active_school_levels:
    - "2"
    - "3"
    - "4"
  :use_gse: false
  :theme: itsisu
  :active_grades:
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
  :site_school: ITSISU school
  :description:
  :site_district: ITSISU district
  :top_level_container_name: unit
  :site_name: ITSISU
  :default_admin_user:
    :first_name: Noah
    :last_name: Paessel
    :login: knowuh
    :email: knowuh@gmail.com
  :states_and_provinces:
    - RI
    - MA
test: *prod
staging: *prod
cucumber: *prod
development: *prod
